### ISSUE TITLE
Host file or CIDR notation of target

### ISSUE THREAD

**Issue by TormentedSoul666** [Cerbrutus-BruteForcer/cerbrutus#1]
Nice approach but why do you limit it to a single host? Almost all common related tools accept a host file or at least a CIDR notation.

**Comment by Cerbrutus-BruteForcer** [comment]
This is still in early stages, and will definitely look into implementing this in the future. Focus for now is on bulking out the network services it will work against.

FTP was added today, hopefully SMB and HTTP will be coming in the next few weeks. There are also plans for an XMLRPC brute forcer for use against Wordpress. 

I’ll keep this in mind for sure!
